name: 'Check inbound changes'

# Triggers
on: [push, workflow_dispatch]

# Jobs
jobs:
  pylint-run:
    # Runs pylint check of code

    runs-on: [ubuntu-latest]
    environment: 'CI'

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint ${PWD}


  black-run:
    # Runs black --check --verbose on the code

    runs-on: [ubuntu-latest]
    environment: 'CI'

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run black check
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."
        version: "~= 24.10.0"
